spring.application.name=bookManagement

# logging level
logging.level.org.springframework.web=debug

# h2 data base
#http://localhost:8080/h2-console/
#: H2 console available at '/h2-console'. Database available at 'jdbc:h2:mem:141cbab5-d6dd-40b8-a17c-abec78f6e90d'
spring.h2.console.enabled=true
spring.datasource.username=root
spring.datasource.password=Password


