spring.application.name=bookManagement
#server.address=localhost
#server.port=8082

# profile (if multiple profile are there than pick last profile property only)
spring.profiles.active[]=dev

# logging level
logging.level.org.springframework.web=debug

# h2 data base
#http://localhost:8080/h2-console/
#: H2 console available at '/h2-console'. Database available at 'jdbc:h2:mem:141cbab5-d6dd-40b8-a17c-abec78f6e90d'
spring.h2.console.enabled=true
spring.datasource.username=root
spring.datasource.password=Password

#kafka setup
    # Kafka Broker Configurations
        #Specifies the Kafka broker’s address.
spring.kafka.bootstrap-servers=localhost:9092
    # topic name define
app.kafka.topic.my-topic=book-events
    # Consumer Configurations
spring.kafka.consumer.group-id= book-consumer-group1
spring.kafka.consumer.auto-offset-reset= earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
    # adding trusted package for BookDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.bookManagement.dto
    # Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#management.endpoint.beans.access=UNRESTRICTED
#management.endpoints.access.default=none
#management.endpoint.env.access=READ_ONLY
management.endpoints.web.exposure.include[]=*
